#!/bin/sh

KERNEL_PATH="drivers\/misc"
SRC="fls_lcd.c"
MODULE="fls_lcd_ik.c"

cat kernel_patch_skel
diff -u /dev/null ./$SRC | sed "s/\/dev\/null.*/a\/$KERNEL_PATH\/$MODULE/" | sed "s/\.\/$SRC.*/b\/$KERNEL_PATH\/$MODULE/"
